### PR TITLE
Fixes attribute name in currency formatter SYNOPSIS.

### PR DESCRIPTION
**Pull request by oalders**

### CODE REVIEW

**Comment by patch** [comment]
Thank you, Olaf!

**Comment by oalders** [comment]
That was faaaaasst. :+1:

**Comment by patch** [comment]
@oalders: This fix was included in CLDR::Number v0.10 and [released to CPAN](https://metacpan.org/release/PATCH/CLDR-Number-0.10).

Thanks again! Also, I was pleased to see CLDR::Number used in GitHub::MergeVelocity :D

**Comment by oalders** [comment]
@patch Thanks for letting me know.  I just recently started using CLDR::Number at maxmind.com to localize our customer-facing pricing.  I appreciate all of your work on this.  It was quite handy to have for GitHub::MergeVelocity as well. :)

**Pull request merged**
